const quizData = {
    "Marvel": [
        { q: "What is the name of Thor's hammer?", a: ["Mjolnir", "Stormbreaker", "Jane Foster", "Jonathan?"], correct: "Mjolnir" },
        { q: "What is Wanda Maximoff's superhero name?", a: ["Scarlet Witch", "Black Widow", "Captain Marvel", "Echo"], correct: "Scarlet Witch" },
        { q: "What is Captain America's shield made of?", a: ["Adamantium", "Vibranium", "Uru", "Titanium"], correct: "Vibranium" },
        { q: "Who is the God of Mischief?", a: ["Thor", "Loki", "Odin", "Hela"], correct: "Loki" },
        { q: "What is the name of the dwarf who forged Stormbreaker?", a: ["Eitri", "Brok", "Sindri", "Glum"], correct: "Eitri" },
        { q: "Which Marvel character has bulletproof skin?", a: ["Luke Cage", "Iron Fist", "The Thing", "Colossus"], correct: "Luke Cage" },
        { q: "What is Peter Parker's middle name?", a: ["Benjamin", "Mary", "John", "Richard"], correct: "Benjamin" },
        { q: "Which stone was inside Vision's forehead?", a: ["Space", "Time", "Mind", "Power"], correct: "Mind" },
        { q: "What is the real name of the Black Panther?", a: ["T'Challa", "M'Baku", "Killmonger", "N'Jadaka"], correct: "T'Challa" },
        { q: "Who was the first Avenger in the MCU timeline?", a: ["Iron Man", "Captain America", "Thor", "Hulk"], correct: "Captain America" },
        { q: "What species is Groot?", a: ["Flora Colossus", "Treeant", "Ent", "Asgardian"], correct: "Flora Colossus" },
        { q: "Who killed Tony Stark's parents?", a: ["Thanos", "Red Skull", "The Winter Soldier", "Obadiah Stane"], correct: "The Winter Soldier" },
        { q: "What is the name of the AI that replaced JARVIS?", a: ["EDITH", "FRIDAY", "KAREN", "ALICE"], correct: "FRIDAY" },
        { q: "In which movie did Spider-Man make his MCU debut?", a: ["Homecoming", "Civil War", "Infinity War", "Endgame"], correct: "Civil War" },
        { q: "What is the name of the planet where the Soul Stone was found?", a: ["Vormir", "Titan", "Knowhere", "Sakaar"], correct: "Vormir" }
    ],
    "DC": [
        { q: "What is the real name of the Joker?", a: ["Jack Napier", "Arthur Fleck", "Unknown", "Joe Chill"], correct: "Unknown" },
        { q: "Which city does The Flash protect?", a: ["Star City", "Gotham", "Central City", "Metropolis"], correct: "Central City" },
        { q: "What drug gives Bane his super strength?", a: ["Titan", "Miraclo", "Venom", "Velocity-9"], correct: "Venom" },
        { q: "Who was the first character in Action Comics #1?", a: ["Batman", "Superman", "Flash", "Wonder Woman"], correct: "Superman" },
        { q: "What is Wonder Woman's weapon called?", a: ["Lasso of Truth", "Spear of Destiny", "Golden Rope", "Trident"], correct: "Lasso of Truth" },
        { q: "What is the name of Batman's butler?", a: ["Alfred Pennyworth", "Jarvis", "Geoffrey", "Hudson"], correct: "Alfred Pennyworth" },
        { q: "Who is the King of Atlantis?", a: ["Namor", "Aquaman", "Ocean Master", "Black Manta"], correct: "Aquaman" },
        { q: "Which green ring-wielder is a pilot?", a: ["Hal Jordan", "John Stewart", "Guy Gardner", "Kyle Rayner"], correct: "Hal Jordan" },
        { q: "What is Superman's birth name?", a: ["Kal-El", "Jor-El", "Zod", "Kara"], correct: "Kal-El" },
        { q: "Who is the sidekick of Batman?", a: ["Robin", "Kid Flash", "Speedy", "Bucky"], correct: "Robin" },
        { q: "Which villain broke Batman's back?", a: ["Joker", "Bane", "Ra's al Ghul", "Penguin"], correct: "Bane" },
        { q: "What is the headquarters of the Justice League?", a: ["Watchtower", "Hall of Justice", "Batcave", "Avengers Tower"], correct: "Watchtower" },
        { q: "Who is the fastest man alive?", a: ["Superman", "The Flash", "Shazam", "Nightwing"], correct: "The Flash" },
        { q: "What is the home planet of Starfire?", a: ["Tamaran", "Krypton", "Mars", "Oa"], correct: "Tamaran" },
        { q: "What is the name of Aquaman's wife?", a: ["Mera", "Iris", "Selina", "Diana"], correct: "Mera" }
    ],
    "Star Wars": [
        { q: "What is the name of Han Solo's iconic ship?", a: ["Enterprise", "Millennium Falcon", "Serenity", "Slave I"], correct: "Millennium Falcon" },
        { q: "What is Baby Yoda's real name?", a: ["Grogu", "Yoda Jr.", "Giddeon", "Grakkus"], correct: "Grogu" },
        { q: "Which planet is home to Chewbacca and the Wookiees?", a: ["Endor", "Kashyyyk", "Hoth", "Tatooine"], correct: "Kashyyyk" },
        { q: "Who is revealed to be Rey's grandfather in Episode IX?", a: ["Obi-Wan", "Palpatine", "Luke", "Count Dooku"], correct: "Palpatine" },
        { q: "What color is Mace Windu's lightsaber?", a: ["Blue", "Green", "Purple", "Yellow"], correct: "Purple" },
        { q: "Who was Anakin Skywalker's Padawan in The Clone Wars?", a: ["Ahsoka Tano", "Barriss Offee", "Rey", "Ventress"], correct: "Ahsoka Tano" },
        { q: "Which character said, 'IT'S A TRAP!'?", a: ["Han Solo", "Luke Skywalker", "Admiral Ackbar", "Lando"], correct: "Admiral Ackbar" },
        { q: "What is the name of the board game played on the Falcon?", a: ["Dejarik", "Sabacc", "Pazaak", "Cyvasse"], correct: "Dejarik" },
        { q: "On which planet did Yoda train Luke?", a: ["Hoth", "Dagobah", "Bespin", "Endor"], correct: "Dagobah" },
        { q: "What is the call sign of Luke Skywalker during the Battle of Yavin?", a: ["Red Leader", "Gold Five", "Red Five", "Blue Two"], correct: "Red Five" },
        { q: "Who built C-3PO?", a: ["Obi-Wan Kenobi", "Anakin Skywalker", "Princess Leia", "Luke Skywalker"], correct: "Anakin Skywalker" },
        { q: "What is the name of the bounty hunter who wears Mandalorian armor?", a: ["Greedo", "Boba Fett", "Bossk", "Dengar"], correct: "Boba Fett" },
        { q: "Which species is known for their scavenging on Tatooine?", a: ["Wookiees", "Ewoks", "Jawas", "Gungans"], correct: "Jawas" },
        { q: "What was the name of the organization that governed the galaxy before the Empire?", a: ["The First Order", "The Republic", "The Alliance", "The Separatists"], correct: "The Republic" },
        { q: "What planet was destroyed by the first Death Star?", a: ["Tatooine", "Alderaan", "Naboot", "Coruscant"], correct: "Alderaan" }
    ],
    "Disney": [
        { q: "What was the first feature-length animated movie released by Disney?", a: ["Pinocchio", "Snow White", "Fantasia", "Dumbo"], correct: "Snow White" },
        { q: "What does 'Hakuna Matata' mean?", a: ["Good Morning", "No Worries", "Stay Strong", "Family First"], correct: "No Worries" },
        { q: "In 'Finding Nemo', what is the address on the goggles?", a: ["42 Wallaby Way", "123 Disney Lane", "10 Downing St", "15 Pixar Road"], correct: "42 Wallaby Way" },
        { q: "Which Disney character famously said, 'Just keep swimming'?", a: ["Nemo", "Marlin", "Dory", "Sebastian"], correct: "Dory" },
        { q: "How many Muses are in the movie 'Hercules'?", a: ["3", "5", "7", "9"], correct: "5" },
        { q: "What high school did Troy and Gabriella attend in High School Musical?", a: ["West High", "East High", "North High", "Disney High"], correct: "East High" },
        { q: "Who composed the music for 'Toy Story'?", a: ["Hans Zimmer", "John Williams", "Randy Newman", "Alan Menken"], correct: "Randy Newman" },
        { q: "What is the name of Belle's father in 'Beauty and the Beast'?", a: ["Gaston", "Lumiere", "Maurice", "LeFou"], correct: "Maurice" },
        { q: "In 'Encanto', which song became a viral #1 hit?", a: ["Surface Pressure", "The Family Madrigal", "We Don't Talk About Bruno", "Dos Oruguitas"], correct: "We Don't Talk About Bruno" },
        { q: "What emotion was the main newcomer in 'Inside Out 2'?", a: ["Envy", "Anxiety", "Ennui", "Embarrassment"], correct: "Anxiety" },
        { q: "What is the name of the dog in 'Up' that can talk?", a: ["Dug", "Russell", "Kevin", "Alpha"], correct: "Dug" },
        { q: "In 'The Little Mermaid', what does Ariel call a fork?", a: ["Dinglehopper", "Snarfblatt", "Thingamabob", "Whoseit"], correct: "Dinglehopper" },
        { q: "Which Disney Princess has a visible tattoo?", a: ["Mulan", "Pocahontas", "Moana", "Rapunzel"], correct: "Pocahontas" },
        { q: "What is the name of the dragon in 'Mulan'?", a: ["Mushu", "Cri-Kee", "Khan", "Shang"], correct: "Mushu" },
        { q: "What is the name of the city where 'Monsters, Inc.' takes place?", a: ["Monstropolis", "Scare City", "Frightville", "Oozma"], correct: "Monstropolis" }
    ],
    "Science": [
        { q: "What is the symbol for Gold?", a: ["Gd", "Ag", "Au", "Pb"], correct: "Au" },
        { q: "Which planet has the most moons?", a: ["Jupiter", "Saturn", "Mars", "Neptune"], correct: "Saturn" },
        { q: "What is the hardest natural substance?", a: ["Gold", "Iron", "Diamond", "Quartz"], correct: "Diamond" },
        { q: "How many bones in the adult human body?", a: ["180", "206", "215", "250"], correct: "206" },
        { q: "What is the liquid metal at room temperature?", a: ["Mercury", "Gallium", "Cesium", "Iron"], correct: "Mercury" },
        { q: "What gas do plants absorb?", a: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correct: "Carbon Dioxide" },
        { q: "Who developed the theory of relativity?", a: ["Newton", "Tesla", "Einstein", "Hawking"], correct: "Einstein" },
        { q: "What is the largest organ in the human body?", a: ["Liver", "Brain", "Skin", "Heart"], correct: "Skin" },
        { q: "What is the speed of light?", a: ["300k km/s", "150k km/s", "1m km/s", "500k km/s"], correct: "300k km/s" },
        { q: "What is the boiling point of water (Celsius)?", a: ["90°C", "100°C", "110°C", "120°C"], correct: "100°C" },
        { q: "Which planet is known as the Red Planet?", a: ["Venus", "Mars", "Jupiter", "Saturn"], correct: "Mars" },
        { q: "What is the closest star to Earth?", a: ["Sirius", "Proxima Centauri", "The Sun", "Vega"], correct: "The Sun" },
        { q: "What is the power house of the cell?", a: ["Nucleus", "Ribosome", "Mitochondria", "Vacuole"], correct: "Mitochondria" },
        { q: "How many elements are in the periodic table?", a: ["100", "118", "125", "112"], correct: "118" },
        { q: "What is the study of mushrooms called?", a: ["Biology", "Mycology", "Botany", "Zoology"], correct: "Mycology" }
    ],
    "Geography": [
        { q: "What is the smallest country?", a: ["Monaco", "Malta", "Vatican City", "San Marino"], correct: "Vatican City" },
        { q: "Which country has the most lakes?", a: ["USA", "Russia", "Canada", "Brazil"], correct: "Canada" },
        { q: "What is the largest hot desert?", a: ["Gobi", "Sahara", "Kalahari", "Arabian"], correct: "Sahara" },
        { q: "In which city are the Spanish Steps?", a: ["Madrid", "Barcelona", "Rome", "Lisbon"], correct: "Rome" },
        { q: "Which river is the longest?", a: ["Amazon", "Nile", "Yangtze", "Mississippi"], correct: "Nile" },
        { q: "What is the capital of Japan?", a: ["Osaka", "Kyoto", "Tokyo", "Hiroshima"], correct: "Tokyo" },
        { q: "Which continent is the driest?", a: ["Africa", "Australia", "Antarctica", "Asia"], correct: "Antarctica" },
        { q: "Which country has the most people (2026)?", a: ["China", "India", "USA", "Indonesia"], correct: "India" },
        { q: "What is the capital of Australia?", a: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: "Canberra" },
        { q: "Which ocean is the largest?", a: ["Atlantic", "Indian", "Arctic", "Pacific"], correct: "Pacific" },
        { q: "In which country is Mount Kilimanjaro?", a: ["Kenya", "Tanzania", "Ethiopia", "Uganda"], correct: "Tanzania" },
        { q: "What is the capital of Canada?", a: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: "Ottawa" },
        { q: "Which country is shaped like a boot?", a: ["Greece", "Italy", "Spain", "Portugal"], correct: "Italy" },
        { q: "What is the tallest mountain?", a: ["K2", "Mount Everest", "Fuji", "Kilimanjaro"], correct: "Mount Everest" },
        { q: "Which sea is the saltiest?", a: ["Red Sea", "Dead Sea", "Black Sea", "Caspian Sea"], correct: "Dead Sea" }
    ],
    "The Year That Was": [
        { q: "Who won the Women's Rugby World Cup 2025?", a: ["New Zealand", "England", "France", "Canada"], correct: "England" },
        { q: "Which band reunited for a global tour in 2025?", a: ["The Beatles", "Oasis", "One Direction", "Led Zeppelin"], correct: "Oasis" },
        { q: "Which city hosted the 2026 Winter Olympics?", a: ["Paris", "Milan-Cortina", "Beijing", "Vancouver"], correct: "Milan-Cortina" },
        { q: "What major film won Best Picture in early 2026?", a: ["Dune 3", "Mickey 17", "Superman", "Avatar 3"], correct: "Mickey 17" },
        { q: "Who won the 2025 Eurovision Contest?", a: ["Sweden", "Austria", "Switzerland", "Croatia"], correct: "Austria" },
        { q: "Which billionaire launched the first private space hotel in 2025?", a: ["Elon Musk", "Jeff Bezos", "Richard Branson", "Yusaku Maezawa"], correct: "Elon Musk" },
        { q: "Which country joined the EU in late 2025?", a: ["Ukraine", "Turkey", "Norway", "Iceland"], correct: "Ukraine" },
        { q: "What was the most downloaded app of 2025?", a: ["TikTok", "Instagram", "Threads", "ChatGPT"], correct: "ChatGPT" },
        { q: "Who won the 2025 Ballon d'Or?", a: ["Mbappe", "Bellingham", "Vinicius Jr", "Haaland"], correct: "Vinicius Jr" },
        { q: "Which tech company reached a $4 trillion valuation in 2025?", a: ["Apple", "Nvidia", "Microsoft", "Google"], correct: "Nvidia" },
        { q: "What is the official name of the 2026 World Cup?", a: ["FIFA 26", "United 2026", "America Cup", "Global 26"], correct: "United 2026" },
        { q: "Which singer had the highest grossing tour of 2025?", a: ["Taylor Swift", "Beyoncé", "Billie Eilish", "Harry Styles"], correct: "Taylor Swift" },
        { q: "What viral dance trend dominated early 2026?", a: ["The Glitch", "Sway", "Robot-Pop", "Moon-Walk"], correct: "The Glitch" },
        { q: "Which video game won Game of the Year in 2025?", a: ["GTA VI", "Death Stranding 2", "Metroid Prime 4", "Fable"], correct: "GTA VI" },
        { q: "Who became the new leader of the Catholic Church in 2025?", a: ["Pope Francis II", "Pope Leo XIV", "Pope John III", "Pope Peter"], correct: "Pope Leo XIV" }
    ],
    "Guinness Records": [
        { q: "Most followed person on Instagram (2026)?", a: ["Selena Gomez", "Messi", "Ronaldo", "The Rock"], correct: "Cristiano Ronaldo" },
        { q: "World's fastest land animal?", a: ["Cheetah", "Pronghorn", "Lion", "Greyhound"], correct: "Cheetah" },
        { q: "Longest breath held underwater?", a: ["15m", "18m", "24m", "30m"], correct: "24m" },
        { q: "Tallest living man?", a: ["Wadlow", "Sultan Kösen", "Yao Ming", "Shaq"], correct: "Sultan Kösen" },
        { q: "Loudest animal on Earth?", a: ["Lion", "Blue Whale", "Sperm Whale", "Monkey"], correct: "Sperm Whale" },
        { q: "Fastest bird?", a: ["Eagle", "Peregrine Falcon", "Ostrich", "Swift"], correct: "Peregrine Falcon" },
        { q: "Most Olympic Gold medals?", a: ["China", "USA", "Russia", "Germany"], correct: "USA" },
        { q: "Longest fingernails ever (Female)?", a: ["Lee Redmond", "Ayanna Williams", "Diana Armstrong", "Chris Walton"], correct: "Diana Armstrong" },
        { q: "Smallest dog breed?", a: ["Pug", "Chihuahua", "Pomeranian", "Yorkie"], correct: "Chihuahua" },
        { q: "Oldest person to ever live?", a: ["Jeanne Calment", "Kane Tanaka", "Jiroemon Kimura", "Sarah Knauss"], correct: "Jeanne Calment" },
        { q: "Most subscribed YouTuber (2026)?", a: ["PewDiePie", "MrBeast", "T-Series", "Cocomelon"], correct: "MrBeast" },
        { q: "Country with most islands?", a: ["Philippines", "Indonesia", "Sweden", "Norway"], correct: "Sweden" },
        { q: "Highest grossing movie?", a: ["Avatar", "Endgame", "Titanic", "Star Wars"], correct: "Avatar" },
        { q: "Longest running TV show?", a: ["Simpsons", "Law & Order", "Doctor Who", "The Price is Right"], correct: "Simpsons" },
        { q: "Most poisonous animal?", a: ["Box Jellyfish", "King Cobra", "Golden Poison Frog", "Stonefish"], correct: "Box Jellyfish" }
    ],
    "World Records": [
        { q: "What is the tallest building in the world?", a: ["Empire State Building", "Burj Khalifa", "Shanghai Tower", "Lotte World Tower"], correct: "Burj Khalifa" },
        { q: "Which animal is the largest to ever live on Earth?", a: ["African Elephant", "Blue Whale", "Megalodon", "Diplodocus"], correct: "Blue Whale" },
        { q: "Who holds the record for the most Olympic Gold medals of all time?", a: ["Usain Bolt", "Michael Phelps", "Simone Biles", "Larisa Latynina"], correct: "Michael Phelps" },
        { q: "Which music video was the first to reach 10 billion views on YouTube?", a: ["Gangnam Style", "Despacito", "Baby Shark Dance", "Shape of You"], correct: "Baby Shark Dance" },
        { q: "What is the world's longest river?", a: ["Amazon", "Mississippi", "The Nile", "Yangtze"], correct: "The Nile" },
        { q: "Who was the world's first centibillionaire (wealth over $100B)?", a: ["Bill Gates", "Jeff Bezos", "Elon Musk", "Warren Buffett"], correct: "Jeff Bezos" },
        { q: "What is the fastest land animal?", a: ["Lion", "Cheetah", "Pronghorn", "Leopard"], correct: "Cheetah" },
        { q: "Which country has the most natural lakes in the world?", a: ["USA", "Russia", "Canada", "Finland"], correct: "Canada" },
        { q: "What is the highest-grossing movie of all time (without inflation)?", a: ["Titanic", "Avengers: Endgame", "Avatar", "Star Wars: Ep VII"], correct: "Avatar" },
        { q: "Who is the youngest person ever to win a Nobel Prize?", a: ["Albert Einstein", "Malala Yousafzai", "Nadia Murad", "Marie Curie"], correct: "Malala Yousafzai" },
        { q: "What is the most recorded song in history?", a: ["Yesterday", "Happy Birthday", "White Christmas", "Imagine"], correct: "Yesterday" },
        { q: "Which planet in our solar system has the most moons?", a: ["Jupiter", "Saturn", "Mars", "Neptune"], correct: "Saturn" },
        { q: "What is the longest a human has ever lived (verified)?", a: ["115 years", "122 years", "125 years", "130 years"], correct: "122 years" },
        { q: "Which video game holds the record for the best-selling game of all time?", a: ["GTA V", "Minecraft", "Tetris", "Wii Sports"], correct: "Minecraft" },
        { q: "What is the deepest point in the world's oceans?", a: ["Mariana Trench", "Java Trench", "Tonga Trench", "Puerto Rico Trench"], correct: "Mariana Trench" }
    ],
    "Yearly Recap": [
        { q: "Which film won the Best Picture Oscar in 2025?", a: ["Oppenheimer", "Anora", "Wicked", "Dune: Part Two"], correct: "Anora" },
        { q: "Who performed the Super Bowl LIX (2025) halftime show in New Orleans?", a: ["Kendrick Lamar", "Usher", "The Weeknd", "Rihanna"], correct: "Kendrick Lamar" },
        { q: "Which city hosted the 2024 Summer Olympic Games?", a: ["Tokyo", "Paris", "London", "Los Angeles"], correct: "Paris" },
        { q: "Which artist's 'Eras Tour' officially became the highest-grossing tour of all time in 2024/25?", a: ["Beyoncé", "Taylor Swift", "Ed Sheeran", "Coldplay"], correct: "Taylor Swift" },
        { q: "What was the name of the viral 'brat summer' album released in 2024?", a: ["BRAT", "SOUR", "GUTS", "Radical Optimism"], correct: "BRAT" },
        { q: "Which animated movie became the highest-grossing of all time in 2024?", a: ["Frozen II", "Inside Out 2", "The Super Mario Bros. Movie", "Toy Story 4"], correct: "Inside Out 2" },
        { q: "What major social media platform was formerly known as Twitter?", a: ["Threads", "X", "Bluesky", "Mastodon"], correct: "X" },
        { q: "In 2025, which artist won the Grammy for Album of the Year for 'Cowboy Carter'?", a: ["Taylor Swift", "Beyoncé", "Billie Eilish", "Sabrina Carpenter"], correct: "Beyoncé" },
        { q: "Which country officially joined NATO as its 32nd member in 2024?", a: ["Finland", "Ukraine", "Sweden", "Switzerland"], correct: "Sweden" },
        { q: "Who broke the record for most career points in NBA history?", a: ["Stephen Curry", "Michael Jordan", "LeBron James", "Kevin Durant"], correct: "LeBron James" },
        { q: "What was the name of the AI model launched by Google to succeed Bard in 2024?", a: ["ChatGPT", "Gemini", "Claude", "Llama"], correct: "Gemini" },
        { q: "Which 2025 live-action Disney remake featured a viral first look at Stitch?", a: ["Moana", "Lilo & Stitch", "Hercules", "Snow White"], correct: "Lilo & Stitch" },
        { q: "Which song by Sabrina Carpenter dominated the charts in the summer of 2024?", a: ["Espresso", "Flowers", "Vampire", "Cruel Summer"], correct: "Espresso" },
        { q: "Who won the 2024 UEFA European Football Championship (Euro 2024)?", a: ["England", "France", "Spain", "Germany"], correct: "Spain" },
        { q: "Which billionaire famously completed the first-ever private spacewalk in 2024?", a: ["Elon Musk", "Jared Isaacman", "Jeff Bezos", "Richard Branson"], correct: "Jared Isaacman" }
    ],
    "Millennial Rewind": [
        { q: "What was the name of the first-ever YouTube video uploaded in 2005?", a: ["Charlie bit my finger", "Me at the zoo", "Evolution of Dance", "Chocolate Rain"], correct: "Me at the zoo" },
        { q: "Which girl group sang the global hit 'Wannabe' in 1996?", a: ["Destiny's Child", "Spice Girls", "TLC", "All Saints"], correct: "Spice Girls" },
        { q: "What was the name of the '90s handheld digital pet you had to feed and clean?", a: ["GameBoy", "Tamagotchi", "Giga Pet", "Furby"], correct: "Tamagotchi" },
        { q: "Which boy band had Justin Timberlake as a member?", a: ["Backstreet Boys", "98 Degrees", "*NSYNC", "New Kids on the Block"], correct: "*NSYNC" },
        { q: "What was the default search engine for many before Google became dominant?", a: ["Bing", "Yahoo!", "Ask Jeeves", "Altavista"], correct: "Yahoo!" },
        { q: "Which social media site was famous for its 'Top 8' friends list?", a: ["Facebook", "MySpace", "Hi5", "Friendster"], correct: "MySpace" },
        { q: "What was the first movie ever released on DVD in the US?", a: ["Twister", "The Matrix", "Titanic", "Jurassic Park"], correct: "Twister" },
        { q: "Which iconic fashion trend featured chunky highlights and low-rise jeans?", a: ["Grunge", "Y2K", "Disco", "Preppy"], correct: "Y2K" },
        { q: "What was the name of the file-sharing service shut down in 2001?", a: ["Napster", "Limewire", "Spotify", "iTunes"], correct: "Napster" },
        { q: "In 'Mean Girls', what color do they wear on Wednesdays?", a: ["Blue", "Red", "Pink", "White"], correct: "Pink" },
        { q: "Which portable music player did Apple launch in 2001?", a: ["Walkman", "Zune", "iPod", "Discman"], correct: "iPod" },
        { q: "What was the name of the high school in 'Saved by the Bell'?", a: ["Bayside High", "West Beverly High", "Degrassi", "Sunnydale High"], correct: "Bayside High" },
        { q: "Which video game console introduced the 'Kinect' sensor?", a: ["PlayStation 3", "Xbox 360", "Nintendo Wii", "GameCube"], correct: "Xbox 360" },
        { q: "What was the name of the viral dancing baby meme from the late '90s?", a: ["Oogachaka Baby", "Baby Shark", "Grumpy Baby", "Dancing Toddler"], correct: "Oogachaka Baby" },
        { q: "Which reality TV show followed the life of Ozzy Osbourne and his family?", a: ["The Real World", "The Osbournes", "The Simple Life", "Jersey Shore"], correct: "The Osbournes" }
    ],
    "History": [
        { q: "In what year did the Berlin Wall fall?", a: ["1987", "1988", "1989", "1991"], correct: "1989" },
        { q: "Who was known as the 'Maid of Orleans'?", a: ["Marie Antoinette", "Joan of Arc", "Catherine the Great", "Queen Elizabeth I"], correct: "Joan of Arc" },
        { q: "Which ancient civilization built the city of Machu Picchu?", a: ["Aztec", "Mayan", "Inca", "Roman"], correct: "Inca" },
        { q: "The Renaissance began in which Italian city?", a: ["Rome", "Venice", "Florence", "Milan"], correct: "Florence" },
        { q: "Who was the first woman to fly solo across the Atlantic Ocean?", a: ["Amelia Earhart", "Sally Ride", "Bessie Coleman", "Harriet Quimby"], correct: "Amelia Earhart" },
        { q: "What was the name of the ship that brought the Pilgrims to America in 1620?", a: ["The Beagle", "The Mayflower", "The Santa Maria", "The Endeavour"], correct: "The Mayflower" },
        { q: "Which empire was ruled by Mansa Musa, the wealthiest person in history?", a: ["Roman Empire", "Mali Empire", "Ottoman Empire", "Aztec Empire"], correct: "Mali Empire" },
        { q: "Who was the first President of the United States?", a: ["Thomas Jefferson", "Benjamin Franklin", "George Washington", "John Adams"], correct: "George Washington" },
        { q: "In which year did the Titanic sink?", a: ["1910", "1912", "1914", "1916"], correct: "1912" },
        { q: "The 'Rosetta Stone' was key to deciphering which language?", a: ["Latin", "Greek", "Egyptian Hieroglyphics", "Sumerian"], correct: "Egyptian Hieroglyphics" },
        { q: "Which English monarch had six wives and broke away from the Catholic Church?", a: ["Henry VII", "Henry VIII", "Richard III", "Edward VI"], correct: "Henry VIII" },
        { q: "What was the name of the plague that killed millions in the 14th century?", a: ["The Spanish Flu", "The Black Death", "The Antonine Plague", "Cholera"], correct: "The Black Death" },
        { q: "Who was the primary leader and founder of the Mongol Empire?", a: ["Kublai Khan", "Genghis Khan", "Attila the Hun", "Tamerlane"], correct: "Genghis Khan" },
        { q: "The Magna Carta was signed by King John of England in which year?", a: ["1066", "1215", "1492", "1776"], correct: "1215" },
        { q: "Which ancient wonder was a massive lighthouse in Egypt?", a: ["Colossus of Rhodes", "Lighthouse of Alexandria", "Hanging Gardens", "Temple of Artemis"], correct: "Lighthouse of Alexandria" }
    ],
    "Art": [
        { q: "Who painted the 'Mona Lisa'?", a: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correct: "Leonardo da Vinci" },
        { q: "Which artist famously cut off part of his own ear?", a: ["Salvador Dalí", "Vincent van Gogh", "Andy Warhol", "Johannes Vermeer"], correct: "Vincent van Gogh" },
        { q: "What art movement is Salvador Dalí associated with?", a: ["Surrealism", "Cubism", "Impressionism", "Pop Art"], correct: "Surrealism" },
        { q: "Who painted the ceiling of the Sistine Chapel?", a: ["Raphael", "Donatello", "Michelangelo", "Leonardo da Vinci"], correct: "Michelangelo" },
        { q: "Which artist is known for his 'Campbell's Soup Cans'?", a: ["Jackson Pollock", "Andy Warhol", "Roy Lichtenstein", "Keith Haring"], correct: "Andy Warhol" },
        { q: "What is the title of Edvard Munch's most famous painting?", a: ["The Starry Night", "The Scream", "The Last Supper", "Guernica"], correct: "The Scream" },
        { q: "Which street artist is famous for being anonymous and secretive?", a: ["Jean-Michel Basquiat", "Banksy", "KAWS", "Shepard Fairey"], correct: "Banksy" },
        { q: "Frida Kahlo was a famous painter from which country?", a: ["Spain", "Mexico", "Argentina", "Colombia"], correct: "Mexico" },
        { q: "Which painting by Vermeer features a girl with a distinct headscarf and earring?", a: ["The Milkmaid", "Girl with a Pearl Earring", "The Night Watch", "The Kiss"], correct: "Girl with a Pearl Earring" },
        { q: "What is the technique of using small, distinct dots of color to form an image?", a: ["Cubism", "Pointillism", "Dadaism", "Fauvism"], correct: "Pointillism" },
        { q: "Who painted 'The Starry Night' while in an asylum at Saint-Rémy-de-Provence?", a: ["Paul Cézanne", "Vincent van Gogh", "Edgar Degas", "Henri Matisse"], correct: "Vincent van Gogh" },
        { q: "Which artist is famous for his 'drip painting' technique?", a: ["Jackson Pollock", "Mark Rothko", "Willem de Kooning", "Georgia O'Keeffe"], correct: "Jackson Pollock" },
        { q: "The 'Statue of David' was sculpted by which artist?", a: ["Bernini", "Donatello", "Michelangelo", "Canova"], correct: "Michelangelo" },
        { q: "In which city is the Louvre Museum located?", a: ["London", "Rome", "Paris", "Berlin"], correct: "Paris" },
        { q: "Which art style is characterized by geometric shapes and multiple viewpoints?", a: ["Abstract Expressionism", "Cubism", "Surrealism", "Realism"], correct: "Cubism" }
    ],
    "Singers": [
        { q: "Which singer is known as the 'King of Pop'?", a: ["Elvis Presley", "Michael Jackson", "Prince", "Freddie Mercury"], correct: "Michael Jackson" },
        { q: "Which singer is famous for the song 'Shape of You'?", a: ["Ed Sheeran", "Justin Bieber", "Shawn Mendes", "Harry Styles"], correct: "Ed Sheeran" },
        { q: "Which artist is known for wearing meat dresses and extravagant outfits?", a: ["Madonna", "Lady Gaga", "Rihanna", "Beyoncé"], correct: "Lady Gaga" },
        { q: "Freddie Mercury was the lead singer of which band?", a: ["The Beatles", "Queen", "Nirvana", "Coldplay"], correct: "Queen" },
        { q: "Which singer is famous for the album '1989'?", a: ["Ariana Grande", "Taylor Swift", "Dua Lipa", "Katy Perry"], correct: "Taylor Swift" },
        { q: "Which singer is known for the hit song 'Rolling in the Deep'?", a: ["Adele", "Sia", "P!nk", "Lorde"], correct: "Adele" },
        { q: "Which artist is often called the 'Queen of Pop'?", a: ["Madonna", "Cher", "Britney Spears", "Celine Dion"], correct: "Madonna" },
        { q: "Which singer became famous with the song 'Baby'?", a: ["Justin Timberlake", "Justin Bieber", "The Weeknd", "Bruno Mars"], correct: "Justin Bieber" },
        { q: "Which singer is known for the album 'Future Nostalgia'?", a: ["Doja Cat", "Dua Lipa", "Billie Eilish", "Olivia Rodrigo"], correct: "Dua Lipa" },
        { q: "Which artist is famous for the song 'Blinding Lights'?", a: ["Drake", "Post Malone", "The Weeknd", "Travis Scott"], correct: "The Weeknd" },
        { q: "Which singer is recognized for her green and black fashion style?", a: ["Billie Eilish", "Selena Gomez", "Camila Cabello", "Halsey"], correct: "Billie Eilish" },
        { q: "Which singer performed 'Someone Like You'?", a: ["Adele", "Sam Smith", "Jessie J", "Kelly Clarkson"], correct: "Adele" },
        { q: "Which artist is known as the 'Rocket Man' singer?", a: ["David Bowie", "Elton John", "Phil Collins", "George Michael"], correct: "Elton John" },
        { q: "Which singer is famous for the hit 'Bad Guy'?", a: ["Olivia Rodrigo", "Billie Eilish", "Demi Lovato", "Sabrina Carpenter"], correct: "Billie Eilish" },
        { q: "Which artist is known for his signature moonwalk dance?", a: ["Usher", "Chris Brown", "Michael Jackson", "Bruno Mars"], correct: "Michael Jackson" }
    ],
    "Instruments": [
        { q: "Which instrument has 88 keys and is commonly used in classical music?", a: ["Violin", "Piano", "Flute", "Trumpet"], correct: "Piano" },
        { q: "Which instrument is known for having six strings and being used in rock music?", a: ["Drums", "Guitar", "Cello", "Clarinet"], correct: "Guitar" },
        { q: "Which instrument is played with a bow and is the smallest in the string family?", a: ["Viola", "Cello", "Violin", "Harp"], correct: "Violin" },
        { q: "Which percussion instrument consists of cymbals, toms, and a snare?", a: ["Xylophone", "Drum Kit", "Tambourine", "Bongo"], correct: "Drum Kit" },
        { q: "Which wind instrument is commonly associated with jazz and made of brass?", a: ["Saxophone", "Oboe", "Recorder", "Bassoon"], correct: "Saxophone" },
        { q: "Which instrument has black and white keys but produces sound using pipes?", a: ["Accordion", "Organ", "Keyboard", "Harpsichord"], correct: "Organ" },
        { q: "Which brass instrument is famous for its long slide?", a: ["Trumpet", "Tuba", "French Horn", "Trombone"], correct: "Trombone" },
        { q: "Which instrument is traditionally associated with Scottish music?", a: ["Banjo", "Bagpipes", "Mandolin", "Ukulele"], correct: "Bagpipes" },
        { q: "Which small string instrument is strongly associated with Hawaiian music?", a: ["Lute", "Ukulele", "Cello", "Bass Guitar"], correct: "Ukulele" },
        { q: "Which instrument is played by blowing across a mouthpiece and is often silver-colored?", a: ["Clarinet", "Flute", "Trombone", "Tuba"], correct: "Flute" },
        { q: "Which large string instrument is usually played while sitting and placed between the knees?", a: ["Violin", "Cello", "Harp", "Banjo"], correct: "Cello" },
        { q: "Which keyboard instrument is electronic and commonly used in pop music?", a: ["Accordion", "Synthesizer", "Xylophone", "Harp"], correct: "Synthesizer" },
        { q: "Which instrument is known for its deep sound and is the largest brass instrument?", a: ["Trumpet", "French Horn", "Tuba", "Trombone"], correct: "Tuba" },
        { q: "Which percussion instrument is made of wooden bars that are struck with mallets?", a: ["Triangle", "Xylophone", "Drum", "Maracas"], correct: "Xylophone" },
        { q: "Which instrument is commonly used in country music and has five strings?", a: ["Mandolin", "Banjo", "Ukulele", "Cello"], correct: "Banjo" }
    ]
};